apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mongodb-backup.fullname" . }}-init-pvc
  labels:
    {{- include "mongodb-backup.labels" . | nindent 4 }}
spec:
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mongodb-backup.serviceAccountName" . }}
      containers:
      - name: init
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: busybox:latest
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /dump
          name: mongo-backup
      restartPolicy: OnFailure
      volumes:
      - name: mongo-backup
        persistentVolumeClaim:
          claimName: {{ include "mongodb-backup.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  backoffLimit: 4
