{{- if .Values.stash.active -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb-backup.fullname" . }}-stash
  labels:
    {{- include "mongodb-backup.labels" . | nindent 4 }}
type: Opaque
data:
{{ if .Values.stash.swift.active }}
  OS_AUTH_URL: {{ .Values.stash.swift.osAuthUrl | b64enc | quote }}
  OS_PROJECT_DOMAIN_NAME: {{ .Values.stash.swift.osProjectDomainName | b64enc | quote }}
  OS_PROJECT_NAME: {{ .Values.stash.swift.osProjectName | b64enc | quote }}
  OS_REGION_NAME: {{ .Values.stash.swift.osRegionName | b64enc | quote }}
  OS_USER_DOMAIN_NAME: {{ .Values.stash.swift.osUserDomainName | b64enc | quote }}
  OS_USERNAME: {{ .Values.stash.swift.osUsername | b64enc | quote }}
  OS_PASSWORD: {{ .Values.stash.swift.osPassword | b64enc | quote }}
{{ end }}
  RESTIC_PASSWORD: {{ .Values.stash.resticPassword | b64enc | quote }}
{{- end }}
